# Generated by Django 3.0.2 on 2020-01-15 00:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shelf', '0002_post_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Shelf',
        ),
    ]
